#!/usr/bin/env python3
"""One-time import: converts the two Google-Sheets xlsx exports into seed.sql.

Normalizations applied (logged to stderr):
- Corolla file prices are in thousands of rupiah -> multiplied by 1000.
- Corolla odometer typo in sessions 3-5: 17000/17500/18000 -> 170000/175000/180000.
- 'Housing Thermostat' row has harga/jumlah swapped (1.0 x 420) -> swapped back.
- Checkpoint cells: datetime -> due_date, number -> due_km, text -> checkpoint_note.
"""
import datetime
import re
import sys

import openpyxl

MONTHS_ID = {
    'januari': 1, 'jan': 1,
    'februari': 2, 'feb': 2,
    'maret': 3, 'mar': 3,
    'april': 4, 'apr': 4,
    'mei': 5,
    'juni': 6, 'jun': 6,
    'juli': 7, 'jul': 7,
    'agustus': 8, 'agt': 8, 'ags': 8, 'agu': 8,
    'september': 9, 'sep': 9,
    'oktober': 10, 'okt': 10,
    'november': 11, 'nov': 11, 'nop': 11,
    'desember': 12, 'des': 12,
}

ODOMETER_FIX = {  # Corolla sessions with a dropped zero
    3: 170000,
    4: 175000,
    5: 180000,
}


def log(msg):
    print(msg, file=sys.stderr)


def parse_date(value):
    """Parse a cell into ISO yyyy-mm-dd. Raises on unrecognized input."""
    if isinstance(value, datetime.datetime):
        return value.date().isoformat()
    if isinstance(value, str):
        s = value.strip()
        # '1-Mei-2025', '4-Agt-2025'
        m = re.fullmatch(r'(\d{1,2})-([A-Za-z]+)-(\d{4})', s)
        if m:
            month = MONTHS_ID[m.group(2).lower()]
            return datetime.date(int(m.group(3)), month, int(m.group(1))).isoformat()
        # '1 Desember 2023'
        m = re.fullmatch(r'(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})', s)
        if m:
            month = MONTHS_ID[m.group(2).lower()]
            return datetime.date(int(m.group(3)), month, int(m.group(1))).isoformat()
        # 'Mei 2025' -> first of month
        m = re.fullmatch(r'([A-Za-z]+)\s+(\d{4})', s)
        if m:
            month = MONTHS_ID[m.group(1).lower()]
            log(f'  month-only date {s!r} -> first of month')
            return datetime.date(int(m.group(2)), month, 1).isoformat()
    raise ValueError(f'unparseable date: {value!r}')


def sql_str(value):
    if value is None:
        return 'NULL'
    return "'" + str(value).replace("'", "''") + "'"


def sql_num(value):
    if value is None:
        return 'NULL'
    return str(value)


class Importer:
    def __init__(self):
        self.vehicles = []     # (id, name)
        self.sessions = []     # (id, vehicle_id, seq, date, odometer_km)
        self.items = []        # dicts
        self.vid = 0
        self.sid = 0

    def add_vehicle(self, name, status):
        self.vid += 1
        self.vehicles.append((self.vid, name, status))
        return self.vid

    def add_session(self, vehicle_id, seq, date, odometer_km):
        self.sid += 1
        self.sessions.append((self.sid, vehicle_id, seq, date, odometer_km))
        return self.sid

    def add_item(self, vehicle_id, session_id, date, description, unit_price, qty,
                 total, category, checkpoint_note, due_date, due_km):
        self.items.append(dict(
            vehicle_id=vehicle_id, session_id=session_id, date=date,
            description=description, unit_price=unit_price, qty=qty, total=total,
            category=category, checkpoint_note=checkpoint_note,
            due_date=due_date, due_km=due_km,
        ))

    def write_sql(self, path):
        """Emit v2 schema: visits (one per session+item-date) + line_items."""
        sess_by_id = {s[0]: s for s in self.sessions}
        visits = []      # [vehicle_id, date, odometer_km, vendor, label, session_id]
        visit_key = {}

        def visit_for(item):
            session = sess_by_id.get(item['session_id']) if item['session_id'] else None
            date = item['date']
            if date is None:
                if session is None:
                    raise ValueError(f'item without date or session: {item["description"]!r}')
                date = session[3]
            key = ('s', session[0], date) if session else ('x', item['vehicle_id'], date)
            if key not in visit_key:
                label = f'Perawatan ke-{session[2]}' if session else None
                visits.append([item['vehicle_id'], date, None, None, label, session[0] if session else None])
                visit_key[key] = len(visits)  # 1-based id
            return visit_key[key]

        item_visit = [visit_for(it) for it in self.items]

        # session odometer -> visit on the session date, else earliest visit
        for sid, vid, seq, date, km in self.sessions:
            cands = [i for i, v in enumerate(visits) if v[5] == sid]
            if not cands:
                continue
            exact = [i for i in cands if visits[i][1] == date]
            target = exact[0] if exact else min(cands, key=lambda i: visits[i][1])
            visits[target][2] = km

        with open(path, 'w') as f:
            f.write('-- Generated by scripts/import_xlsx.py — do not edit by hand.\n')
            for vid, name, status in self.vehicles:
                f.write(f'INSERT INTO vehicles (id, name, status) '
                        f'VALUES ({vid}, {sql_str(name)}, {sql_str(status)});\n')
            for i, (vehicle_id, date, km, vendor, label, _sid) in enumerate(visits, 1):
                f.write(f'INSERT INTO visits (id, vehicle_id, date, odometer_km, vendor, label) '
                        f'VALUES ({i}, {vehicle_id}, {sql_str(date)}, {sql_num(km)}, '
                        f'{sql_str(vendor)}, {sql_str(label)});\n')
            for it, vi in zip(self.items, item_visit):
                f.write(
                    'INSERT INTO line_items (visit_id, description, unit_price, qty, total, '
                    'category, checkpoint_note, due_date, due_km, checkpoint_done) VALUES ('
                    f"{vi}, {sql_str(it['description'])}, {it['unit_price']}, {it['qty']}, "
                    f"{it['total']}, {sql_str(it['category'])}, {sql_str(it['checkpoint_note'])}, "
                    f"{sql_str(it['due_date'])}, {sql_num(it['due_km'])}, 0);\n"
                )
        log(f'  ({len(visits)} visits)')


def parse_checkpoint(cell):
    """-> (note, due_date, due_km)"""
    if cell is None:
        return None, None, None
    if isinstance(cell, datetime.datetime):
        return None, cell.date().isoformat(), None
    if isinstance(cell, (int, float)):
        return None, None, int(cell)
    return str(cell).strip(), None, None


def parse_money(value, scale):
    if value is None:
        return None
    return int(round(float(value) * scale))


def import_session_sheet(imp, ws, vehicle_id, scale, odometer_fix):
    """Parse a sheet structured as repeated 'Perawatan ke' blocks."""
    rows = list(ws.iter_rows(values_only=True))
    session_id = None
    seq = None
    header_date = None
    header_km = None
    last_date = None
    for row in rows:
        a, b, c, d, e, ftot, g = (list(row) + [None] * 7)[:7]
        if c == 'Perawatan ke':
            seq = int(d)
            header_date = None
            header_km = None
            session_id = None
            continue
        if c == 'Tanggal' and seq is not None and session_id is None:
            header_date = parse_date(d)
            continue
        if c == 'Kilometer' and seq is not None and session_id is None:
            header_km = int(d)
            if odometer_fix and seq in odometer_fix:
                log(f'  odometer fix: session {seq} km {header_km} -> {odometer_fix[seq]}')
                header_km = odometer_fix[seq]
            session_id = imp.add_session(vehicle_id, seq, header_date, header_km)
            last_date = None
            continue
        if c in (None, 'Parts / Jasa') or session_id is None:
            continue  # blank, header, or total-only row

        description = str(c).strip()
        if b is not None:
            last_date = parse_date(b)
        date = last_date

        if d is None and e is None and ftot is None:
            # umbrella row like 'Servis Power Steering' — children carry the costs
            unit_price, qty, total = 0, 0, 0
        else:
            unit_price = parse_money(d, scale)
            qty = float(e) if e is not None else 1.0
            if description == 'Housing Thermostat' and d is not None and e is not None \
                    and float(d) < float(e) and float(e) > 50:
                log(f'  swapped harga/jumlah fixed: {description} '
                    f'({d} x {e} -> {e} x {d})')
                d, e = e, d
                unit_price, qty = parse_money(d, scale), float(e)
            if unit_price is None:
                raise ValueError(f'row has total but no price: {row!r}')
            if ftot is None:
                total = int(round(unit_price * qty))
                log(f'  missing total computed: {description} -> {total}')
            else:
                total = parse_money(ftot, scale)

        note, due_date, due_km = parse_checkpoint(g)
        imp.add_item(vehicle_id, session_id, date, description, unit_price, qty,
                     total, 'rutin', note, due_date, due_km)


def import_flat_sheet(imp, ws, vehicle_id, scale, category, grouped):
    """Parse a flat table sheet (Aksesoris, Balik Nama)."""
    rows = list(ws.iter_rows(values_only=True))
    group = None
    last_date = None
    for row in rows:
        a, b, c, d, e, ftot = (list(row) + [None] * 6)[:6]
        if c in (None, 'Parts / Jasa', 'Keterangan') and not (grouped and isinstance(a, str)):
            continue
        if grouped and isinstance(a, str):  # group label row like 'Sisi DKI (asal)'
            group = a.strip()
            continue
        description = str(c).strip()
        if group:
            description = f'{group}: {description}'
        if b is not None:
            last_date = parse_date(b)
        unit_price = parse_money(d, scale)
        qty = float(e)
        total = parse_money(ftot, scale)
        imp.add_item(vehicle_id, None, last_date, description, unit_price, qty,
                     total, category, None, None, None)


def main():
    imp = Importer()

    log('=== Histori Perawatan Corolla Twincam.xlsx (prices x1000) ===')
    wb = openpyxl.load_workbook('Histori Perawatan Corolla Twincam.xlsx', data_only=True)
    corolla = imp.add_vehicle('Corolla Twincam', 'active')
    import_session_sheet(imp, wb['Perawatan Rutin'], corolla, 1000, ODOMETER_FIX)
    import_flat_sheet(imp, wb['Aksesoris'], corolla, 1000, 'aksesoris', grouped=False)
    import_flat_sheet(imp, wb['Balik Nama'], corolla, 1000, 'administratif', grouped=True)

    log('=== Histori Perawatan Motor.xlsx (prices as-is) ===')
    wb = openpyxl.load_workbook('Histori Perawatan Motor.xlsx', data_only=True)
    revo = imp.add_vehicle('Revo Fit 2012', 'sold')  # sold, replaced by Vixion
    import_session_sheet(imp, wb['Revo Fit 2012'], revo, 1, None)
    mio = imp.add_vehicle('Mio Smile 2010', 'active')
    import_session_sheet(imp, wb['Mio Smile 2010'], mio, 1, None)
    imp.add_vehicle('Yamaha All New Vixion 2017', 'active')  # no history yet

    imp.write_sql('seed.sql')
    log(f'wrote seed.sql: {len(imp.vehicles)} vehicles, '
        f'{len(imp.sessions)} sessions, {len(imp.items)} line items')

    # sanity: totals per vehicle
    for vid, name, _status in imp.vehicles:
        total = sum(i['total'] for i in imp.items if i['vehicle_id'] == vid)
        log(f'  {name}: Rp {total:,}')


if __name__ == '__main__':
    main()
